services:
    postgres:
        image: postgres:15
        container_name: ecommerce_db
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

    redis:
        image: redis:7-alpine
        container_name: ecommerce_redis
        ports:
            - "${REDIS_PORT}:6379"
        restart: unless-stopped

volumes:
    postgres_data:
