version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/project

jobs:
  test:
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Set up virtualenv
          command: |
            python -m venv .venv
            source .venv/bin/activate

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "requirements.txt" }}
            - v1-deps-

      - run:
          name: Install Python dependencies
          command: |
            source .venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - .venv
          key: v1-deps-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests with coverage
          command: |
            source .venv/bin/activate
            coverage run manage.py test
            coverage report
            coverage xml

      - store_artifacts:
          path: coverage.xml
          destination: coverage

workflows:
  version: 2
  test-and-build:
    jobs:
      - test

      