apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          # image: kimanikevin254/drf-ecommerce-api:latest
          image: ecommerce_api:local
          imagePullPolicy: Never
          command: ["celery", "-A", "ecommerce_api", "worker", "--loglevel=info"]
          envFrom:
            - configMapRef:
                name: ecommerce-api-config
            - secretRef:
                name: ecommerce-api-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"