apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-api-config
data:
  DJANGO_SETTINGS_MODULE: "ecommerce_api.settings_prod"
  DB_NAME: {{DB_NAME}}
  DB_USER: {{DB_USER}}
  DB_HOST: {{DB_HOST}}
  DB_PORT: {{DB_PORT}}
  REDIS_URL: {{REDIS_URL}}
  AFRICASTALKING_USERNAME: {{AFRICASTALKING_USERNAME}}
  REDIS_PORT: {{REDIS_PORT}}
